//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadPerformance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreadPerformance.Resources.MainView", typeof(MainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string btnDE_Content {
            get {
                return ResourceManager.GetString("btnDE_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string btnEN_Content {
            get {
                return ResourceManager.GetString("btnEN_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbage.
        /// </summary>
        internal static string BtnGC_Content {
            get {
                return ResourceManager.GetString("BtnGC_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open thread window.
        /// </summary>
        internal static string btnOpenWindow_Content {
            get {
                return ResourceManager.GetString("btnOpenWindow_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open window.
        /// </summary>
        internal static string btnOpenWindow2_Content {
            get {
                return ResourceManager.GetString("btnOpenWindow2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon description.
        /// </summary>
        internal static string icon_ToolTip {
            get {
                return ResourceManager.GetString("icon_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip one.
        /// </summary>
        internal static string item1_ToolTip {
            get {
                return ResourceManager.GetString("item1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip two.
        /// </summary>
        internal static string item2_ToolTip {
            get {
                return ResourceManager.GetString("item2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item description.
        /// </summary>
        internal static string itemHeader_ToolTip {
            get {
                return ResourceManager.GetString("itemHeader_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab description.
        /// </summary>
        internal static string tabHeader_ToolTip {
            get {
                return ResourceManager.GetString("tabHeader_ToolTip", resourceCulture);
            }
        }
    }
}
