//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlLocalizationTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTextsDuplicateKeysDifferentValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTextsDuplicateKeysDifferentValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamlLocalizationTest.Resources.ResTextsDuplicateKeysDifferentValues", typeof(ResTextsDuplicateKeysDifferentValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageTest {
            get {
                object obj = ResourceManager.GetObject("ImageTest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORMALE Resource_Duplicate.
        /// </summary>
        internal static string resBack {
            get {
                return ResourceManager.GetString("resBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red_Duplicate.
        /// </summary>
        internal static string resColor {
            get {
                return ResourceManager.GetString("resColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORMALER TITEL_Duplicate.
        /// </summary>
        internal static string resTitel {
            get {
                return ResourceManager.GetString("resTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORMAL Resource_Duplicate.
        /// </summary>
        internal static string resTop {
            get {
                return ResourceManager.GetString("resTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TaskName.
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
    }
}
