//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFLocalizationExtensionDemoApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFLocalizationExtensionDemoApplication.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Examples_A_DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("Examples.A.DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shop in {0} is open on {1} from {2} to {3}, that&apos;s on {4}.
        /// </summary>
        internal static string Examples_A_ShopInCityOpenWithReprise {
            get {
                return ResourceManager.GetString("Examples.A.ShopInCityOpenWithReprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test without placeholder.
        /// </summary>
        internal static string Examples_B_NoPlaceholder {
            get {
                return ResourceManager.GetString("Examples.B.NoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Test with {0}..
        /// </summary>
        internal static string Examples_C_TestWithPlaceholder {
            get {
                return ResourceManager.GetString("Examples.C.TestWithPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} lived {0} years ago..
        /// </summary>
        internal static string Examples_D_TestWithReorderedControls {
            get {
                return ResourceManager.GetString("Examples.D.TestWithReorderedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Examples_GapTextWpfExample_CityLabel {
            get {
                return ResourceManager.GetString("Examples.GapTextWpfExample.CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example {0}.
        /// </summary>
        internal static string Examples_GapTextWpfExample_Example {
            get {
                return ResourceManager.GetString("Examples.GapTextWpfExample.Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Toolbar_LanguageLabel {
            get {
                return ResourceManager.GetString("Toolbar.LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Toolbar_VersionLabel {
            get {
                return ResourceManager.GetString("Toolbar.VersionLabel", resourceCulture);
            }
        }
    }
}
